using Microsoft.AspNetCore.Mvc;
using QuarterlySales.Models.Validation;
using System.ComponentModel.DataAnnotations;

namespace QuarterlySales.Models
{
    public class Employee
    {
        //Primary Key - generated by DB
        public int EmployeeId { get; set; }

        [Required(ErrorMessage = "Please enter a first name.")]
        [StringLength(100)]
        [Display(Name = "First Name")]
        public string FirstName { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please enter a last name.")]
        [StringLength(100)]
        [Display(Name = "Last Name")]
        public string LastName { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please enter a date of birth.")]
        [PastDate]
        [Remote("CheckEmployee", "Validation", AdditionalFields = "FirstName, LastName")]
        [Display(Name = "Birth Date")]
        public DateTime? DOB { get; set; }

        [Required(ErrorMessage = "Please enter a date of hire.")]
        [PastDate]
        [GreaterThan("1/1/1995", ErrorMessage = "Hire date must be after company was formed (1/1/1995).")]
        [Display(Name = "Hire Date")]
        public DateTime? DateOfHire { get; set; }   

        [GreaterThan(0, ErrorMessage = "Please select a manager.")]
        [Remote("CheckManager", "Validation", AdditionalFields = "FirstName, LastName, DOB")]
        [Display(Name = "Manager")]
        public int ManagerId { get; set; }

        //read-only properties
        public string FullName => $"{FirstName} {LastName}";

        public string Slug => FirstName?.Replace(' ', '-').ToLower()
            + '-' + LastName?.Replace(' ', '=').ToLower();
    }
}