using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using QuarterlySales.Models.Validation;
using System.ComponentModel.DataAnnotations;

namespace QuarterlySales.Models
{
    public class Sales
    {
        //Primary Key - generated by DB
        public int SalesId { get; set; }

        [Required(ErrorMessage = "Please enter a Quarter.")]
        [Range(1, 4, ErrorMessage = "Quarter must be between 1 and 4.")]
        public int? Quarter { get; set; }

        [Required(ErrorMessage = "Please enter a Year.")]
        [GreaterThan(2000, ErrorMessage = "Year must be after 2000.")]
        public int? Year { get; set; }

        [Required(ErrorMessage = "Please enter an Amount.")]
        [GreaterThan(0.0, ErrorMessage = "Amount must be greater than zero.")]
        public double? Amount { get; set; }

        //Foreign Key
        [GreaterThan(0, ErrorMessage = "Please select an Employee.")]
        [Remote("CheckSales", "Validation", AdditionalFields = "Quarter, Year")]
        [Display(Name = "Employee")]
        public int EmployeeId { get; set; }

        //Navigation Property
        [ValidateNever]
        public Employee Employee { get; set; } = null!;
    }
}
